### ISSUE TITLE
memory leak detected

### ISSUE THREAD

**Issue by bastianwegge** [rosshinkley/mongoose-revisionist#2] opened 2015-10-19 07:32 UTC
Hey @rosshinkley,

I've found some error as your current version of mongoose-revisionist does not work.

(node) warning: possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit.
Trace

```
    at process.addListener (events.js:239:17)
    at Object.module.exports.exports [as setup] (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/tests/util/setup.js:12:13)
    at Object.module.exports.exports.setUp (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/tests/methods/getVersionByDate.js:13:18)
    at /Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/lib/core.js:260:35
    at /Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:458:21
    at /Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:163:13
    at iterate (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:123:13)
    at async.forEachSeries (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:139:9)
    at _asyncMap (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:162:9)
    at Object.mapSeries (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:152:23)
    at Object.async.series (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/deps/async.js:456:19)
    at Object.<anonymous> (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/lib/core.js:264:22)
    at Object.<anonymous> (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/lib/core.js:228:19)
    at Object.<anonymous> (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/lib/core.js:236:16)
    at Object.<anonymous> (/Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/lib/core.js:236:16)
    at /Users/bastianwegge/dev/prototypes/mongoose-revisionist/node_modules/nodeunit/lib/core.js:236:16
```

Any questions? Feel free to @ me :+1:

**Comment by rosshinkley** [comment] 2015-10-19 16:58
The library should still work fine - the memory leak is a warning, not a breaking exception.  I have been able to reproduce this.  I assume you were simply trying to run the unit tests?

I had tuned my local install of node in such a way to suppress these warnings when revisionist was being written.  I will take a look at this ASAP and see if I can fix it.

**Comment by rosshinkley** [comment] 2015-10-20 21:42
The problem is actually simpler than I thought: each setup redoes the error handler for the process (which is not correct), and that's what is tripping the event emitter leak.  I had been in the throes of migrating this project off of nodeunit and to mocha which allows for suite-level hooks.  This will ensure the exception handler is added only once, as well as preventing mongoose connection thrashing.  I'll keep you posted when I get that finished.

**Comment by bastianwegge** [comment] 2015-10-20 21:47
Great thank you!

**Comment by rosshinkley** [comment] 2015-10-21 13:57
@bastianwegge Should be good to go now.  Closing this item.  Let me know if you need anything else.

**Closed as completed by rosshinkley** 2015-10-21 13:57 UTC
